### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by SekiAlpha** [Virizion/Corpses#1]
[16:32:14 ERROR]: Could not pass event EntityDamageByEntityEvent to PvPManager v3.3.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.MobEffectList.applyInstantEffect(MobEffectList.java:139) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityPotion.a(EntityPotion.java:118) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityProjectile.t_(EntityProjectile.java:154) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
        at org.bukkit.craftbukkit.v1_8_R3.scoreboard.CraftTeam.checkState(CraftTeam.java:217) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.craftbukkit.v1_8_R3.scoreboard.CraftTeam.addEntry(CraftTeam.java:142) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at me.NoChance.PvPManager.PvPlayer.setTagged(SourceFile:3080) ~[?:?]
        at nc.dt.c(SourceFile:2148) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        ... 24 more

**Comment by egold555** [comment]
Download the new version of the plugin here: https://www.spigotmc.org/resources/corpsereborn.29875/
